In [8]:
import pandas as pd

In [9]:
m200 = pd.read_csv('DATA/OUTPUT/MHW_summary_table_long_oisst.19812025.Portugal_200m_bathymetry.csv')
m400 = pd.read_csv('DATA/OUTPUT/MHW_summary_table_long_oisst.19812025.Portugal_400m_bathymetry.csv')
m600 = pd.read_csv('DATA/OUTPUT/MHW_summary_table_long_oisst.19812025.Portugal_600m_bathymetry.csv')
m800 = pd.read_csv('DATA/OUTPUT/MHW_summary_table_long_oisst.19812025.Portugal_800m_bathymetry.csv')
m1000 = pd.read_csv('DATA/OUTPUT/MHW_summary_table_long_oisst.19812025.Portugal_1000m_bathymetry.csv')
m200.head()

   Year  Month Zone              Parameter  Value
0  1981      9   NW  activity_degC_days_m2    0.0
1  1981      9   NW    mean_intensity_degC    NaN
2  1981     10   NW  activity_degC_days_m2    0.0
3  1981     10   NW    mean_intensity_degC    NaN
4  1981     11   NW  activity_degC_days_m2    0.0

In [10]:
m200['Bathymetry'] = 200
m400['Bathymetry'] = 400
m600['Bathymetry'] = 600
m800['Bathymetry'] = 800
m1000['Bathymetry'] = 1000

In [20]:
concatenated = pd.concat([m200, m400, m600, m800, m1000])
concatenated.to_csv('DATA/OUTPUT/allBat_Concatenated_SummaryTable_long.csv', index= False)
concatenated.to_excel('DATA/OUTPUT/allBat_Concatenated_SummaryTable_long.xlsx', index= False)

In [18]:
concatenated

      Year  Month Zone              Parameter      Value  Bathymetry
0     1981      9   NW  activity_degC_days_m2   0.000000         200
1     1981      9   NW    mean_intensity_degC        NaN         200
2     1981     10   NW  activity_degC_days_m2   0.000000         200
3     1981     10   NW    mean_intensity_degC        NaN         200
4     1981     11   NW  activity_degC_days_m2   0.000000         200
...    ...    ...  ...                    ...        ...         ...
5527  2025     11   SW    mean_intensity_degC   1.312799        1000
5528  2025     11   SW       number_of_events   2.000000        1000
5529  2025     11   SW           sum_area_km2  67.415036        1000
5530  2025     12   SW  activity_degC_days_m2   0.000000        1000
5531  2025     12   SW    mean_intensity_degC        NaN        1000

[26732 rows x 6 columns]

In [19]:
concat200_400 = pd.concat([m200, m400])
concat200_400.to_csv('DATA/OUTPUT/200and400m_Concatenated_SummaryTable_long.csv', index= False)
concat200_400.to_excel('DATA/OUTPUT/200and400m_Concatenated_SummaryTable_long.xlsx', index= False)